### ISSUE TITLE
bad naming of manifest.json when fingerprints = false

### ISSUE THREAD

**Issue by ZiperRom1** [arthurbergmz/webpack-pwa-manifest#57] opened 2018-04-08 04:22 UTC
When the option `fingerprints` is set to `false`, the output name of manifest is `manifest..json` instead of  `manifest.json` (double dot)

**Comment by seiryokusan** [comment] 2018-05-04 17:02
Not sure if this helps but it was not occurring on 3.4.1. I've only seen this on 3.6.2 so far.

**Comment by christophermiles** [comment] 2018-05-13 03:37
Happening for me on 3.6.2 too

**Comment by doug-wade** [comment] 2018-07-27 17:21
Duplicate of #64

**Closed by doug-wade** 2018-07-27 17:21 UTC
